# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['TheFunc.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends._backend_tk',
        'numpy.core',
        'numpy.lib.format',
        'numpy.f2py',
        'scipy.special',
        'scipy.stats',
        'scipy.sparse',
        'scipy.spatial',
        'scipy._lib._ccallback_c',
        'scipy._lib.array_api_compat.numpy',
        'scipy._lib.array_api_compat._internal',
        'scipy.linalg',
        'scipy.linalg._fblas',
        'scipy.linalg._flapack',
        'PIL.Image',
        'PIL.ImageTk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes = [
        'scipy.io',
        'scipy.misc',
        'scipy.odr',
        'scipy.cluster',
        'matplotlib.tests',
        'matplotlib.testing',
        'matplotlib.backends.backend_webagg',
        'matplotlib.backends.web_backend',
        'matplotlib.backends.backend_gtk3agg',
        'matplotlib.backends.backend_gtk3cairo',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_qt5cairo',
        'matplotlib.backends.backend_wxagg',
        'matplotlib.backends.backend_wxcairo',
        'matplotlib.backends.backend_macosx',
        'numpy.tests',
        'numpy.doc',
        'numpy.distutils',
        'tkinter.test',
        'tkinter.dnd',
        'pytest',
        'setuptools',
        'pip',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TheFunc',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        '_shortest_path.cp313-win_amd64.pyd',
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='TheFunc.ico',
)